name: 🪄 Optimize Images Once

on:
  workflow_dispatch:  # You will run this manually from the Actions tab

permissions:
  contents: write

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install optimization tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick webp

      - name: Optimize all JPG and PNG images
        run: |
          mkdir -p optimized
          find img -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | while read IMG; do
            echo "Optimizing $IMG ..."
            convert "$IMG" -resize 800x800\> -strip -quality 80 "optimized/$(basename "$IMG")"
          done
          mv optimized/* img/

      - name: Commit optimized images
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add img/
          git commit -m "🪄 One-time image optimization" || echo "No images changed"
          git push
